<?php

namespace App;

use Illuminate\Database\Eloquent\Model;


class Tread extends Model {
    
    protected $guarded = [];



    //Global global scope
    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::addGlobalScope('replyCount', function ($builder){
            $builder->withCount('replies');
        } );


    }

    /**
     * @return string Path to Tread
     */
    public function path() {

        return "/treads/{$this->channel->slug}/{$this->id}";
    }



    public function owner() {
        
        return $this->belongsTo(User::class, 'user_id');
        
    }
    
    public function replies() {
        return $this->hasMany(Reply::class);
    }
    
    public function addReply($reply) {
        $this->replies()->create($reply);
        
        
    }
    
    public function channel() {
        
        return $this->belongsTo(Channel::class);
        
    }

    /**
     * @param $query
     * @param $filter
     */
    public function scopeFilter($query, $filter){

        return $filter->apply($query);

    }


}
